networks:
  app-network:

volumes:
  postgres_data:
  modules_files:

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: nginx
    ports:
      - 443:443
    networks:
      - app-network
    depends_on:
      - front-end
      - back-end
    env_file:
      - .env
    restart: on-failure

  back-end:
    container_name: backend
    image: backend
    build:
      context: backend
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

  front-end:
    container_name: frontend
    image: frontend
    build: ./frontend
    networks:
      - app-network
    depends_on:
      - back-end
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/posgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - app-network
    restart: on-failure
