version: '3.8'

networks:
  app-network:

volumes:
  postgres_data:

services:
  back-end:
    container_name: backend
    command: python manage.py runserver 0:8000
    image: backend
    build:
      context: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/code
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17beta1
    volumes:
      - postgres_data:/var/lib/posgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - app-network
